/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as CartoonsRouteImport } from './routes/cartoons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchMediaTypeIdRouteImport } from './routes/watch.$mediaType.$id'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoonsRoute = CartoonsRouteImport.update({
  id: '/cartoons',
  path: '/cartoons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMediaTypeIdRoute = WatchMediaTypeIdRouteImport.update({
  id: '/watch/$mediaType/$id',
  path: '/watch/$mediaType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoons': typeof CartoonsRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$mediaType/$id': typeof WatchMediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoons': typeof CartoonsRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$mediaType/$id': typeof WatchMediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoons': typeof CartoonsRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$mediaType/$id': typeof WatchMediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoons'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv'
    | '/watch/$mediaType/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoons'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv'
    | '/watch/$mediaType/$id'
  id:
    | '__root__'
    | '/'
    | '/cartoons'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/tv'
    | '/watch/$mediaType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoonsRoute: typeof CartoonsRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  TvRoute: typeof TvRoute
  WatchMediaTypeIdRoute: typeof WatchMediaTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoons': {
      id: '/cartoons'
      path: '/cartoons'
      fullPath: '/cartoons'
      preLoaderRoute: typeof CartoonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$mediaType/$id': {
      id: '/watch/$mediaType/$id'
      path: '/watch/$mediaType/$id'
      fullPath: '/watch/$mediaType/$id'
      preLoaderRoute: typeof WatchMediaTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoonsRoute: CartoonsRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  TvRoute: TvRoute,
  WatchMediaTypeIdRoute: WatchMediaTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
